### ISSUE TITLE
Tone slide is not working correctly.

### ISSUE THREAD

**Issue by cornelisser** [cornelisser/TriloTracker-Re-player#12]
Tone slides work not as expected.

**Comment by cornelisser** [comment]
Fixed!
Was a bug in the resetiing od the command flag and wrong delay timing.

**Comment by artrag** [comment]
Great!! 
Ps
do I need to compile the tmu files again?

**Comment by cornelisser** [comment]
No. The music fornat is still the same.

Regards,
Richard

Verstuurd vanaf mijn iPhone
