### ISSUE TITLE
Speedequalization 2.0

### ISSUE THREAD

**Issue by cornelisser** [cornelisser/TriloTracker-Re-player#20]
Implement the changes of the tracker in the replayer.

Affected routine is :replay_process_chan_AY

**Comment by artrag** [comment]
Is this feature the one that allows to play at 50Hz the audio even if the ISR is at 60Hz?

**Comment by cornelisser** [comment]
Hi Arturo,

Yes. But this is an improved version. There is already an existing
equalization in the re-player.
The difference is that the instruments (like drums) are always played each
interrupt.  Whilst the music notes are only processed 5 of 6 ISRs when in
60Hz.

Regards,
Richard

2016-09-05 1:20 GMT+02:00 artrag <notifications@github.com>:

**Comment by cornelisser** [comment]
Implemented.

**Comment by cornelisser** [comment]
Hi Arturo,

I just updated the re-player on github to support the speed equalization.
Just set the 'equalization_freq' variable to 0 for 50Hz and any other value
for 60Hz after you call "replay_init".

It is safe to switch the value of the variable at any time.

Regards,
Richard

2016-09-05 10:58 GMT+02:00 Richard Cornelisse <richard@trilobyte-msx.com>:
