### ISSUE TITLE
differences with TT

### ISSUE THREAD

**Issue by artrag** [cornelisser/TriloTracker-Re-player#22]
Sme TMU files once compiled do not sound correctly in the replayer
I've mailed you two TMU files and their compiled version with the ASM to build the rom

**Comment by cornelisser** [comment]
Issue in one of the songs (SHIP) is caused by instrument 8. 
By changing the data of instrument 8 to the one of 7 no issue are noticeable.

**Comment by cornelisser** [comment]
Issue in song SHIP is solved. 
There was a bug in the compiler where note deviations was exported when there was no noise bit set.
Behavior is now same between tracker and re-player.

**Comment by cornelisser** [comment]
Issue with EX song was caused by two things:
1. The songs did not have a base volume in channel 1. This resulted in silent drums
2. The replayer has an issue handling the noise deviation. Fixed it.
