### ISSUE TITLE
Song example and Replayer 3.1 version

### ISSUE THREAD

**Issue by alberto-nlk** [cornelisser/TriloTracker-Re-player#29]
Hi! 
The song (USAS by Gryzor) can't be player correctly with the new 3.1 version but can be player perfectly with the version 3.0. I have disassembled the ROM code of the demos and I have detected that this demos are compiled with the 3.0 version. 
Does It the 3.1 version stable? Do I need to recompile TMU again for 3.1?
Thank you!

**Comment by cornelisser** [comment]
Hi Alberto,

I will look into this this week. I'm not sure what the issue is. I hope to
update you with a solution soon.

Regards,
Richard

2017-07-05 19:27 GMT+02:00 Alberto De Hoyo Nebot <notifications@github.com>:

**Comment by cornelisser** [comment]
Hi Alberto,

Apollogies for my late reply.

I suggest using the latest version of the re-player and the tracker.
I have solved some important bugs in it, with the help of the team who
created Who Dares Wins 2.

Please compile the song with the latest compiler to be sure the data is
correct.

After that there were no other bug reports. I also have no plans to add new
features of fixes to the tracker and replayer at the moment. The only
updates would be on the SFX part. Which have no effect on the replayer for
the music.

I hope to have helped you.

Regards,
Richard

<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virusvrij.
www.avg.com
<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

2017-07-10 13:13 GMT+02:00 Richard Cornelisse <richard@trilobyte-msx.com>:
