### ISSUE TITLE
Compiler doesn't work with tmu exports from the FM tracker

### ISSUE THREAD

**Issue by basalicante** [cornelisser/TriloTracker-Re-player#65]
Hi! I'm trying to use the replayer for the first time. So maybe I'm doing something wrong, sorry if that's the case :-)

I get an error when trying to convert a .tmu from the FM version of the tracker. It seems like it's getting a type "9" in the first byte of the .tmu, which should not be possible - as far as I can tell, only 0,1 and 3 should be allowed. In this case the first 4 bytes should be 0001 for the FM version.

When I manually change the 9 to 1, it crashed for other reasons, I imagine the compiler is not compatible with the later versions of the tracker?

Ah, and when trying an old version ( TT_0_10_0b.dsk ) it DOES start with 0001, so it's something that stopped working later on.

Thanks for your help,
bas

**Comment by cornelisser** [comment]
This specific issue has been fixed. Will be solved in another story. (#66)
